AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

StringLiterals:
  Enabled: false

AssignmentInCondition:
  Enabled: false